load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "rospy_message_converter",
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//ROS/third_party/rospy_message_converter/src/rospy_message_converter:all_modules",
    ],
)
